import { useEffect, useRef, useState } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { site } from "../lib/site";

gsap.registerPlugin(ScrollTrigger);

// Relative public paths so the built site also works opened from disk
// (vite.config base "./").
// The static fallback uses the clean final frame.
const POSTER = "hero/hero-scrub-poster.jpg";
const POSTER_WEBP = "hero/hero-scrub-poster.webp";
// Phones get a portrait frame — the 16:9 still crops down to an unreadable
// sliver of car on a tall screen.
const POSTER_MOBILE = "hero/hero-poster-portrait.jpg";
const POSTER_MOBILE_WEBP = "hero/hero-poster-portrait.webp";

// Frame sequence for the scrub (generated by scripts/gen-hero-frames.mjs
// from the source MP4s — 72 WebP frames per clip, zero-padded, q75).
const FRAME_COUNT = 72;
const frameSrc = (mode: "desktop" | "mobile", i: number) =>
  `hero/frames-${mode}/frame-${String(i + 1).padStart(3, "0")}.webp`;

/**
 * Scroll-scrubbed frame-sequence hero.
 *
 * The hero pins for ~200vh and scroll position picks a frame from a WebP
 * image sequence, drawn to a canvas — scrolling down advances the valet
 * film, scrolling up reverses it. This replaced video.currentTime seeking,
 * which iOS WebKit throttles during touch-scroll gestures (the scrub froze
 * on real phones); image draws have no such restriction.
 *
 * Frame 1 is an eager <img> under the canvas (the LCP paint, dirty first
 * frame). Frames 2–72 load sequentially at low priority after the window
 * load event, each decoded off the render path via img.decode() before
 * being marked usable — the scrub maps scroll to the nearest LOADED frame,
 * so it degrades gracefully mid-download. Frames are held as plain <img>
 * elements and drawn direct (no ImageBitmap cache — 72 decoded bitmaps
 * would be ~270 MB and gets the tab killed on iOS; the browser manages
 * its own decoded-image memory and can evict under pressure).
 *
 *  - desktop (≥768px): the landscape sequence
 *  - mobile  (<768px): the portrait sequence, shot for phone screens
 *  - static: prefers-reduced-motion, or a save-data / 2G connection —
 *    a still of the clean final frame, no sequence downloaded at all.
 */
type Mode = "desktop" | "mobile" | "static";

type NetworkInfo = { saveData?: boolean; effectiveType?: string };

function resolveMode(): Mode {
  const reducedMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)",
  ).matches;
  const connection = (navigator as Navigator & { connection?: NetworkInfo })
    .connection;
  const constrained =
    connection?.saveData === true ||
    connection?.effectiveType === "slow-2g" ||
    connection?.effectiveType === "2g";
  if (reducedMotion || constrained) return "static";
  return window.matchMedia("(min-width: 768px)").matches ? "desktop" : "mobile";
}

export default function Hero() {
  const sectionRef = useRef<HTMLElement>(null);
  const pinRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const hintRef = useRef<HTMLDivElement>(null);
  // Resolved synchronously (lazy initializer, runs once before first paint)
  // rather than defaulting to "desktop" and correcting in an effect — the
  // old default briefly rendered the desktop <video src> on every mobile
  // visit, kicking off a request for the much larger desktop file that
  // then had to be aborted once the real mode landed.
  const [mode, setMode] = useState<Mode>(resolveMode);

  useEffect(() => {
    const queries = [
      window.matchMedia("(min-width: 768px)"),
      window.matchMedia("(prefers-reduced-motion: reduce)"),
    ];
    const update = () => setMode(resolveMode());
    queries.forEach((q) => q.addEventListener("change", update));
    return () =>
      queries.forEach((q) => q.removeEventListener("change", update));
  }, []);

  useEffect(() => {
    if (mode === "static") return;

    const canvas = canvasRef.current;
    if (!canvas) return;
    const drawCtx = canvas.getContext("2d");
    if (!drawCtx) return;

    let cancelled = false;
    const frames: (HTMLImageElement | null)[] = new Array(FRAME_COUNT).fill(
      null,
    );
    // Frames load sequentially, so "loaded" is always a contiguous prefix.
    let maxLoaded = -1;
    // Fractional frame position — kept fractional so adjacent frames can be
    // crossfaded. 72 discrete frames over ~2 viewport-heights of scroll is
    // only ~7 frame changes/sec at a slow deliberate scroll speed (measured)
    // — visibly steppy even at a rock-solid 60fps. Blending neighbour
    // frames by the fractional part lifts the CONTENT update rate to the
    // display rate.
    let requestedF = 0;
    let drawnF = -1;

    // The crop is biased upward on desktop (object-[center_60%] on the old
    // video): the point 60% down the frame aligns with 60% down the box.
    const focalY = mode === "desktop" ? 0.6 : 0.5;

    const drawOne = (img: HTMLImageElement, alpha: number) => {
      const cw = canvas.width;
      const ch = canvas.height;
      const iw = img.naturalWidth;
      const ih = img.naturalHeight;
      if (!cw || !ch || !iw || !ih) return;
      const scale = Math.max(cw / iw, ch / ih);
      const dw = iw * scale;
      const dh = ih * scale;
      drawCtx.globalAlpha = alpha;
      drawCtx.drawImage(img, (cw - dw) / 2, (ch - dh) * focalY, dw, dh);
      drawCtx.globalAlpha = 1;
    };

    // The browser evicts decoded frame data long before we revisit a frame
    // (72 decoded frames is far over its cache budget), so an unprimed
    // drawImage forces a SYNCHRONOUS main-thread re-decode — measured at
    // 50–160ms per frame under 4× CPU throttle, the dominant jank source
    // on slower devices. decode() re-primes the cache asynchronously, so
    // warming the frames just ahead of the scrub direction keeps draws
    // cheap. (Still no ImageBitmap cache — we never own decoded memory.)
    let lastPrimed = -1;
    const primeAhead = (base: number, direction: number) => {
      if (base === lastPrimed) return;
      lastPrimed = base;
      for (let k = 1; k <= 3; k++) {
        const idx = base + k * direction;
        if (idx >= 0 && idx < FRAME_COUNT) frames[idx]?.decode().catch(() => {});
      }
    };

    // Adaptive quality: the crossfade doubles per-tick draw work, which a
    // fast desktop absorbs invisibly but a slow phone cannot (measured:
    // rAF p50 doubled under 4× CPU throttle during fast scrolls). Track an
    // exponential moving average of real draw cost and drop the blend —
    // single-frame draws, like the pre-crossfade behaviour — while this
    // device is struggling. Slow devices get the old stepping, fast ones
    // get fluid blending; nobody gets jank we can avoid.
    let drawCostEma = 0;

    const renderRequested = () => {
      const f = Math.min(requestedF, maxLoaded);
      if (f < 0 || Math.abs(f - drawnF) < 0.02) return;
      const base = Math.floor(f);
      const frac = f - base;
      const baseImg = frames[base];
      if (!baseImg) return;
      const blend = drawCostEma < 20;
      const nextImg =
        blend && frac > 0.01 ? frames[Math.min(base + 1, maxLoaded)] : null;
      const t0 = performance.now();
      drawOne(baseImg, 1);
      if (nextImg && nextImg !== baseImg) drawOne(nextImg, frac);
      drawCostEma = drawCostEma * 0.8 + (performance.now() - t0) * 0.2;
      primeAhead(base, f >= drawnF ? 1 : -1);
      drawnF = f;
    };

    // Canvas backing store tracks the box size (DPR capped at 2 — 3× is
    // invisible extra work on a moving image).
    const fit = () => {
      const box = canvas.getBoundingClientRect();
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.round(box.width * dpr);
      canvas.height = Math.round(box.height * dpr);
      drawnF = -1; // resizing clears the canvas — force a redraw
      renderRequested();
    };
    fit();
    window.addEventListener("resize", fit);

    const loadFrame = (index: number) =>
      new Promise<void>((resolve) => {
        const img = new Image();
        if (index > 0) {
          (img as HTMLImageElement & { fetchPriority?: string }).fetchPriority =
            "low";
        }
        img.src = frameSrc(mode, index);
        img
          .decode()
          .then(() => {
            if (cancelled) return;
            frames[index] = img;
            maxLoaded = index;
            // If the visitor has scrolled ahead of the download, catch up.
            renderRequested();
          })
          .catch(() => {
            /* a missing frame just stays skipped — nearest loaded wins */
          })
          .finally(resolve);
      });

    // Frame 1 immediately (cache-hit — the eager <img> below already
    // fetched it); the rest sequentially once the page has loaded, so the
    // sequence never competes with critical-path resources. EXCEPT: the
    // first scroll/touch is intent to scrub — at that point the frames ARE
    // the critical resource, so start at once instead of letting the scrub
    // sit sticky on frame 1 while below-fold images finish. (LCP is
    // unaffected: by the time the visitor interacts, the hero has painted.)
    let restStarted = false;
    const startRest = () => {
      if (restStarted || cancelled) return;
      restStarted = true;
      (async () => {
        for (let i = 1; i < FRAME_COUNT && !cancelled; i++) {
          await loadFrame(i);
        }
      })();
    };
    loadFrame(0);
    if (document.readyState === "complete") {
      startRest();
    } else {
      window.addEventListener("load", startRest, { once: true });
      window.addEventListener("scroll", startRest, { once: true, passive: true });
      window.addEventListener("touchstart", startRest, { once: true, passive: true });
    }

    const ctx = gsap.context(() => {
      ScrollTrigger.create({
        trigger: pinRef.current,
        start: "top top",
        end: "+=200%",
        pin: true,
        // Small smoothing (not a hard link): with 72 discrete frames, a
        // hard-linked scrub lands every wheel tick as a quantized step
        // with zero easing — reads as "sticky". 0.5s of catch-up glides
        // through the intermediate frames instead.
        scrub: 0.5,
        onUpdate: (self) => {
          requestedF = self.progress * (FRAME_COUNT - 1);
          renderRequested();
          if (hintRef.current) {
            hintRef.current.style.opacity = self.progress > 0.02 ? "0" : "1";
          }
        },
        // When the catch-up settles, snap to the nearest whole frame so a
        // stopped scroll never rests on a soft two-frame blend.
        onScrubComplete: (self) => {
          requestedF = Math.round(self.progress * (FRAME_COUNT - 1));
          renderRequested();
        },
      });

      // No loading screen in front of the hero — entrance plays immediately.
      gsap.fromTo(
        ".name-reveal",
        { opacity: 0, y: 50 },
        { opacity: 1, y: 0, duration: 1.1, ease: "power3.out", delay: 0.1 },
      );
      gsap.fromTo(
        ".blur-in",
        { opacity: 0, y: 20, filter: "blur(10px)" },
        {
          opacity: 1,
          y: 0,
          filter: "blur(0px)",
          duration: 0.9,
          ease: "power3.out",
          delay: 0.2,
          stagger: 0.1,
        },
      );
    }, sectionRef);

    return () => {
      cancelled = true;
      window.removeEventListener("resize", fit);
      window.removeEventListener("load", startRest);
      window.removeEventListener("scroll", startRest);
      window.removeEventListener("touchstart", startRest);
      ctx.revert();
    };
  }, [mode]);

  return (
    <section
      ref={sectionRef}
      id="home"
      aria-label="Aqua Valet — premium valeting, Cork"
    >
      <div ref={pinRef} className="relative h-hero overflow-hidden bg-black">
        {/* Media sits BELOW the fixed header (md+) so the header never covers
            the car, and the crop is biased upward — the car's roof is at 20.5%
            of the frame and the tyres at 85.5%, so a centred crop on a short
            laptop window clips the roof.
            Offset matches the header's collapsed (scrolled) height, not its
            taller resting height with the info strip — the hero pins almost
            immediately on scroll, so the header is in its collapsed state for
            virtually the entire pinned scroll. A larger offset here left a
            permanent gap below the collapsed header once the info strip
            stopped being sticky. */}
        <div className="absolute inset-0 md:top-16">
        {mode !== "static" ? (
          // key forces a fresh img/canvas pair when swapping sequences
          // across the breakpoint
          <div key={mode} className="relative h-full w-full">
            {/* Frame 1 as a real <img>: the eager LCP paint (dirty first
                frame), visible until the canvas starts drawing over it —
                same pixels, so the takeover is invisible. */}
            <img
              src={frameSrc(mode, 0)}
              alt=""
              width={mode === "mobile" ? 720 : 1536}
              height={mode === "mobile" ? 1296 : 854}
              loading="eager"
              decoding="async"
              className="h-full w-full object-cover md:object-[center_60%]"
              aria-hidden="true"
            />
            <canvas
              ref={canvasRef}
              className="absolute inset-0 h-full w-full"
              aria-hidden="true"
            />
          </div>
        ) : (
          <picture>
            <source
              type="image/webp"
              media="(min-width: 768px)"
              srcSet={POSTER_WEBP}
            />
            <source type="image/webp" srcSet={POSTER_MOBILE_WEBP} />
            <source media="(min-width: 768px)" srcSet={POSTER} />
            <img
              src={POSTER_MOBILE}
              alt="A gleaming black premium SUV in the Aqua Valet studio after a full deep clean"
              width={828}
              height={1792}
              className="h-full w-full object-cover md:object-[center_60%]"
            />
          </picture>
        )}
        </div>

        {/* Subtle dark overlay + bottom fade for text legibility */}
        <div className="absolute inset-0 bg-black/40 md:bg-black/30" aria-hidden="true" />
        {/* Phones: extra top-down scrim so the headline stays crisp over the
            brighter part of the frame */}
        <div
          className="absolute inset-x-0 top-0 h-2/3 bg-gradient-to-b from-ink/85 via-ink/35 to-transparent md:hidden"
          aria-hidden="true"
        />
        <div
          className="absolute inset-x-0 bottom-0 h-48 bg-gradient-to-t from-ink to-transparent"
          aria-hidden="true"
        />

        {/* Content — no z-index: a stacking context here would trap the
            lockup's mix-blend-screen away from the video behind it; DOM
            order already paints this above the overlays. Left-aligned over
            the dark space per the vwash-ref-2 framing (structure only). */}
        {/* Phones: text at the top, buttons pinned low, so the car reads in
            the clear band between them rather than sitting behind the CTAs.
            md+ keeps the single centred stack. */}
        <div className="relative mx-auto flex h-full w-full max-w-[1320px] flex-col items-start justify-between px-6 pb-28 pt-32 text-left sm:px-6 md:justify-center md:pb-0 md:pt-24 lg:px-10">
          <div className="w-full">
            <p className="blur-in text-xs uppercase tracking-[0.3em] text-ink-muted">
              Premium Valeting — Cork
            </p>
            <h1 className="name-reveal font-display mt-5 max-w-3xl text-ink-text text-[2.6rem] font-extrabold leading-[0.95] tracking-tight sm:text-5xl md:mt-6 md:text-7xl lg:text-8xl">
              Your car, <em className="not-italic text-accent">restored</em>.
            </h1>
            {/* Sub-copy + rating: desktop only (xl, matching the header's
                hamburger cutover) — on phones/tablets they crowded the car
                out of the clear band between headline and CTAs. */}
            <p className="blur-in mt-5 hidden max-w-md text-balance text-base text-ink-muted md:mt-6 xl:block">
              Deep-clean specialists for people who care about their car. Eight
              years in Cork. By appointment only.
            </p>
            <p className="blur-in mt-4 hidden items-center gap-2 text-sm text-ink-muted xl:flex">
              <span className="text-accent" aria-hidden="true">
                ★★★★★
              </span>
              <span>
                {site.rating} · {site.reviewCount} Google reviews
              </span>
            </p>
          </div>
          <div className="blur-in mt-8 flex w-full flex-col gap-3 sm:w-auto sm:flex-row sm:items-center sm:gap-4 md:mt-9">
            <a
              href="#book"
              className="rounded-full bg-ink-text px-7 py-3.5 text-center text-base font-medium text-ink ring-2 ring-transparent transition hover:bg-ink hover:text-ink-text hover:ring-accent focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
            >
              Get a Photo Quote
            </a>
            <a
              href="#pricing"
              className="rounded-full border border-white/25 px-7 py-3.5 text-center text-base font-medium text-ink-text transition hover:border-accent focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
            >
              View Packages
            </a>
          </div>
        </div>

        {/* Scroll cue — fades out once scrubbing starts */}
        {mode !== "static" && (
          <div
            ref={hintRef}
            aria-hidden="true"
            className="absolute bottom-8 left-1/2 z-10 -translate-x-1/2 text-center transition-opacity duration-500"
          >
            <p className="text-xs uppercase tracking-[0.2em] text-ink-muted">
              Scroll to reveal
            </p>
            <div className="mx-auto mt-3 h-10 w-px overflow-hidden bg-ink-stroke">
              <div className="animate-scroll-down h-full w-full bg-ink-text" />
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
